const emojis = [
    {emoji:'😀',name:'笑脸'},
    {emoji:'😁',name:'呲牙'},
    {emoji:'🙂',name:'微笑'},
    {emoji:'😆',name:'笑眯眯'},
    {emoji:'😅',name:'傻笑'},
    {emoji:'🤣',name:'笑死'},
    {emoji:'😂',name:'笑哭'},
    {emoji:'😉',name:'眨眼'},
    {emoji:'😇',name:'圣母笑'},
    {emoji:'🥰',name:'真心微笑'},
    {emoji:'😍',name:'色色'},
    {emoji:'😘',name:'轻吻'},
    {emoji:'😋',name:'美味'},
    {emoji:'😜',name:'吐舌头'},
    {emoji:'🤑',name:'见钱眼开'},
    {emoji:'🤭',name:'偷笑'},
    {emoji:'🤫',name:'安静'},
    {emoji:'🤗',name:'开怀微笑'},
    {emoji:'🤔',name:'思考'},
    {emoji:'🤐',name:'闭嘴'},
    {emoji:'🤨',name:'挑眉'},
    {emoji:'🙄',name:'翻白眼'},
    {emoji:'😪',name:'打瞌睡'},
    {emoji:'🤤',name:'流口水'},
    {emoji:'😴',name:'睡觉'},
    {emoji:'🤮',name:'吐'},
    {emoji:'🥵',name:'热'},
    {emoji:'🥶',name:'冷'},
    {emoji:'😵',name:'晕'},
    {emoji:'🤠',name:'牛仔'},
    {emoji:'😎',name:'酷'},
    {emoji:'🧐',name:'戴眼镜'},
    {emoji:'😕',name:'困惑'},
    {emoji:'😲',name:'惊讶'},
    {emoji:'😳',name:'脸红'},
    {emoji:'😥',name:'伤心'},
    {emoji:'😭',name:'大哭'},
    {emoji:'😱',name:'惊吓'},
    {emoji:'🥱',name:'困'},
    {emoji:'😡',name:'生气'},
    {emoji:'😤',name:'越想越气'},
    {emoji:'😈',name:'恶魔'},
    {emoji:'💀',name:'骷髅'},
    {emoji:'💩',name:'屎'},
    {emoji:'🤡',name:'小丑竟是我自己'},
    // {emoji:'👻',name:'鬼魂'},
    // {emoji:'👽',name:'外星人'},
    // {emoji:'🤖',name:'机器人'},
    // {emoji:'😺',name:'猫'},
    // {emoji:'💋',name:'亲吻'},
    // {emoji:'👋',name:'挥手'},
    // {emoji:'👌',name:'OK'},
    // {emoji:'✌️',name:'YES'},
    // {emoji:'👍',name:'GOOD'},
    // {emoji:'👊',name:'拳头'},
    // {emoji:'👏',name:'鼓掌'},
    // {emoji:'🤝',name:'握手'},
    // {emoji:'🙏',name:'保佑'}
]

const emoji = {
    emojis
}

export default emoji